# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "timm_mobilenetv2"
runtime_library = "libtrtmc_model_timm_mobilenetv2.so"
runtime_plugins = ["plugin.cpp|register_timm_mobilenetv2_plugin"]
runtime_strategies = ["timm_mobilenetv2_image_classification"]
runtime_tests = [
  "test_timm_mobilenetv2_image_preprocess_seam|test_timm_mobilenetv2_image_preprocess_seam.cpp|trtmc_model_timm_mobilenetv2|_|_",
]
