# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "timm_crossvit"
plugin = "timm_crossvit"
module = "plugin"
python_profile_specs = [
  "timm_crossvit_reference|families/timm_crossvit/python_profile_requirements/timm_crossvit_reference.lock.txt|families/timm_crossvit/python_profile_verify.py|true",
]
default_execution_profiles = [
  "reference|timm_crossvit_reference",
]
aliases = [
  "timm_crossvit",
  "crossvit_9_240",
]
prefixes = [
  "timm_crossvit",
  "crossvit",
]
