# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "qwen3_omni"
plugin = "qwen3_omni"
module = "plugin"
aliases = [
  "qwen3_omni",
  "qwen3_omni_moe",
  "qwen3omni",
]
prefixes = [
  "qwen3_omni",
]
