# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "dpr"
runtime_library = "libtrtmc_model_dpr.so"
runtime_plugins = ["plugin.cpp|register_dpr_plugin"]
runtime_strategies = ["dpr_encoder_only"]
runtime_tests = [
  "test_dpr_encoder_pipeline|test_dpr_encoder_pipeline.cpp|trtmc_model_dpr,trtmc_backend_trt|_|REQUIRES_TRT",
]
