# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "xlnet"
plugin = "xlnet"
module = "plugin"
aliases = [
  "xlnet",
]
prefixes = [
  "xlnet",
]
