# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "timesfm"
aliases = [
  "times_fm",
  "timesfm",
]
prefixes = [
  "times_fm",
  "timesfm",
]
