# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "timm_efficientnet"
runtime_library = "libtrtmc_model_timm_efficientnet.so"
runtime_plugins = ["plugin.cpp|register_timm_efficientnet_plugin"]
runtime_strategies = ["timm_efficientnet_image_classification"]
runtime_tests = [
  "test_timm_efficientnet_image_preprocess_seam|test_timm_efficientnet_image_preprocess_seam.cpp|trtmc_model_timm_efficientnet|_|_",
]
