# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#Requires -Version 5.1

[CmdletBinding()]
param(
    [string]$WorkspaceRoot,
    [string]$ElectronRoot,
    [string]$OutputRoot
)
$ErrorActionPreference = 'Stop'
if (-not $WorkspaceRoot) { $WorkspaceRoot = (Resolve-Path (Join-Path $PSScriptRoot '../../..')).Path }
$WorkspaceRoot = [IO.Path]::GetFullPath($WorkspaceRoot)
if (!$ElectronRoot) { $ElectronRoot = Join-Path $WorkspaceRoot 'dependencies/electron' }
if (!$OutputRoot) { $OutputRoot = Join-Path $WorkspaceRoot 'Nemotron Voice Lab' }
$OutputRoot = [IO.Path]::GetFullPath($OutputRoot)
$workspacePrefix = $WorkspaceRoot.TrimEnd('\', '/') + [IO.Path]::DirectorySeparatorChar
if (-not $OutputRoot.StartsWith($workspacePrefix, [StringComparison]::OrdinalIgnoreCase)) {
    throw 'OutputRoot must be a directory inside WorkspaceRoot so the generated launcher can use a relative path.'
}
if (!(Test-Path (Join-Path $ElectronRoot 'electron.exe'))) { throw "Electron is missing at $ElectronRoot" }
New-Item -ItemType Directory -Force $OutputRoot | Out-Null
$sourceExecutable = Join-Path $ElectronRoot 'electron.exe'
$installedExecutable = Join-Path $OutputRoot 'electron.exe'
$runtimeMatches = (Test-Path -LiteralPath $installedExecutable) -and
    ((Get-FileHash -LiteralPath $sourceExecutable).Hash -eq (Get-FileHash -LiteralPath $installedExecutable).Hash)
if (!$runtimeMatches) {
    Copy-Item -Path (Join-Path $ElectronRoot '*') -Destination $OutputRoot -Recurse -Force
}
$appRoot = Join-Path $OutputRoot 'resources/app'
New-Item -ItemType Directory -Force $appRoot | Out-Null
foreach ($item in @('package.json', 'main.js', 'preload.js', 'protocol.js', 'diagnostics.js', 'renderer')) {
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot "desktop/$item") -Destination $appRoot -Recurse -Force
}
# Assemble only on the user's PC. This local output includes downloaded Electron;
# it is not a source-release archive and must not be uploaded with the example.
$appExecutable = Join-Path $OutputRoot 'Nemotron Voice Lab.exe'
if (!(Test-Path -LiteralPath $appExecutable) -or
    (Get-FileHash -LiteralPath $installedExecutable).Hash -ne (Get-FileHash -LiteralPath $appExecutable).Hash) {
    Copy-Item -LiteralPath $installedExecutable -Destination $appExecutable -Force
}
$appRelative = $OutputRoot.Substring($workspacePrefix.Length)
$launchScript = @'
# Local launcher generated by the source example. Move the whole workspace together.
$ErrorActionPreference = 'Stop'
$appRoot = Join-Path $PSScriptRoot '__APP_RELATIVE__'
$previousWorkspace = $env:VOICE_LAB_WORKSPACE
$previousElectronMode = $env:ELECTRON_RUN_AS_NODE
try {
    $env:VOICE_LAB_WORKSPACE = $PSScriptRoot
    Remove-Item Env:ELECTRON_RUN_AS_NODE -ErrorAction SilentlyContinue
    Start-Process -FilePath (Join-Path $appRoot 'Nemotron Voice Lab.exe') -WorkingDirectory $appRoot -WindowStyle Normal
} finally {
    $env:VOICE_LAB_WORKSPACE = $previousWorkspace
    $env:ELECTRON_RUN_AS_NODE = $previousElectronMode
}
'@
$launchScript = $launchScript.Replace('__APP_RELATIVE__', $appRelative.Replace("'", "''"))
Set-Content -LiteralPath (Join-Path $WorkspaceRoot 'Start Voice Lab.ps1') -Value $launchScript -Encoding utf8
Write-Output "Assembled locally: $OutputRoot"
