id = "gpt_neox"
runtime_library = "libtrtmc_model_gpt_neox.so"
runtime_plugins = ["plugin.cpp|register_gpt_neox_plugin"]
runtime_strategies = ["gpt_neox_decoder_kv_cache"]
[validation_profiles]
decoder_debug = ["gpt_neox_decoder_kv_cache"]
