# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "albert"
plugin = "albert"
module = "plugin"
aliases = [
  "albert",
]
prefixes = [
  "albert",
]
