#!/usr/bin/env bash
set -euo pipefail

stage="${1:?usage: run-gha-stage.sh <stage>}"

container_name="${TRTMC_CI_CONTAINER_NAME:-trtmc-ci-${GITHUB_RUN_ID:-local}-${GITHUB_RUN_ATTEMPT:-0}}"

if [ "$(docker inspect -f '{{.State.Running}}' "$container_name" 2>/dev/null || true)" != "true" ]; then
  echo "::error::CI container '$container_name' is not running. Start it with .github/scripts/start-gha-container.sh before running stages."
  exit 1
fi

docker exec \
  -w "$GITHUB_WORKSPACE" \
  -e CI_BASE_REF \
  -e ENGINE_DIR \
  -e TRTMC_STORAGE_ROOT \
  -e HF_HOME \
  -e HF_HUB_CACHE \
  -e HUGGINGFACE_HUB_CACHE \
  -e HF_MODULES_CACHE \
  -e FULL_E2E \
  -e RUN_COVERAGE_MAP \
  -e REBUILD_ENGINES \
  -e GITHUB_EVENT_NAME \
  -e GITHUB_REF_NAME \
  -e GITHUB_RUN_ID \
  -e GITHUB_RUN_ATTEMPT \
  -e TRTMC_CI_PREMERGE \
  -e TRTMC_CI_STATE_DIR \
  -e TRTMC_E2E_EXCLUDE_GPU0 \
  -e TRTMC_E2E_DEPRIORITIZE_GPU0 \
  -e TRTMC_TRT_TIMING_CACHE_PATH \
  -e TRTMC_TRT_TIMING_CACHE_DIR \
  -e TRTMC_BUILDER_OPTIMIZATION_LEVEL \
  -e TRTMC_MAX_NUM_TACTICS \
  -e TRTMC_AVG_TIMING_ITERATIONS \
  -e TRTMC_ENABLE_LIBTORCH_MULTINOMIAL \
  -e PYTHONHASHSEED \
  -e PYTHON_COVERAGE_MIN_LINE \
  -e PYTHON_COVERAGE_MIN_BRANCH \
  -e CPP_COVERAGE_MIN_LINE \
  -e CPP_COVERAGE_MIN_FUNCTION \
  -e CPP_COVERAGE_MIN_BRANCH \
  -e BUILD_ALL_TIMEOUT \
  -e CPP_UNIT_TIMEOUT \
  -e PYTHON_BUILDER_TIMEOUT \
  -e CPP_COVERAGE_TIMEOUT \
  -e CPP_COVERAGE_BUILD_DIR \
  -e GRAPH_OP_TIMEOUT \
  -e SELECTIVE_E2E_TIMEOUT \
  -e FULL_E2E_TIMEOUT \
  -e COVERAGE_MAP_TIMEOUT \
  -e TRTMC_PACKAGE_PYTHON_TAGS \
  -e TRTMC_PACKAGE_WHEEL_ARCH \
  -e TRTMC_PACKAGE_BUILD_ROOT \
  -e TRTMC_WHEEL_QWEN_MODEL_ID \
  -e TRTMC_WHEEL_QWEN_MAX_CACHE \
  -e TRTMC_WHEEL_QWEN_MAX_NEW_TOKENS \
  -e TRTMC_WHEEL_QWEN_OPTIMIZATION_LEVEL \
  -e TRTMC_WHEEL_QWEN_BUILD_TIMEOUT \
  -e TRTMC_WHEEL_QWEN_RUN_TIMEOUT \
  -e DIFFUSION_VLM_ASSESSMENT \
  -e DIFFUSION_VLM_MODEL_ID \
  -e DIFFUSION_VLM_MAX_SIDE \
  -e DIFFUSION_VLM_MAX_NEW_TOKENS \
  -e DIFFUSION_VLM_TIMEOUT \
  -e HF_TOKEN \
  -e HUGGING_FACE_HUB_TOKEN \
  "$container_name" \
  bash .github/scripts/run-trtmc-ci.sh "$stage"
