/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// =============================================================================
// ISO 26262 Traceability
// =============================================================================
// Trace ID:       UT-SEG-CPP-03-SAM2-HOI
// Architecture:   ARCH-MODPLUG-001
// Unit Design:    UD-SEG-01
// Intent:         SAM2 HOI image preprocessing, mask postprocessing, and NPY I/O
// Preconditions:  RGB pixels and mask logits have declared contiguous shapes
// Postconditions: Pillow/SAM2/NumPy boundary contracts are preserved exactly
// =============================================================================

#include "runtime/models/sam2_hoi/sam2_hoi_io.h"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <iterator>
#include <limits>
#include <string>
#include <vector>

namespace {

int g_failures = 0;

void check(bool condition, const char* name) {
    if (!condition) {
        std::cerr << "FAIL: " << name << '\n';
        ++g_failures;
    }
}

void check_close(float actual, float expected, float tolerance, const char* name) {
    if (std::fabs(actual - expected) > tolerance) {
        std::cerr << "FAIL: " << name << " actual=" << actual << " expected=" << expected << '\n';
        ++g_failures;
    }
}

void test_bicubic_resize_matches_pillow_rgb_golden() {
    // Golden generated by Pillow 12.3.0:
    // Image.fromarray(source, "RGB").resize((3, 3), Image.Resampling.BICUBIC)
    const std::vector<uint8_t> source{
        0,   10, 20,  64,  74, 84, 192, 202, 212, 255, 245, 235,
        255, 0,  128, 192, 32, 96, 64,  224, 48,  0,   255, 16,
    };
    const std::vector<uint8_t> expected{
        0,   19,  22,  128, 140, 154, 255, 241, 251, 128, 9, 76,  128, 134,
        111, 128, 249, 129, 255, 0,   129, 128, 127, 67,  0, 255, 7,
    };
    const auto actual = trtmc::sam2_hoi::resize_pillow_bicubic_rgb_u8(source.data(), 2, 4, 3, 3);
    check(actual == expected, "SAM2 HOI bicubic resize matches Pillow RGB golden");
}

void test_bicubic_resize_matches_pillow_single_column_boundary() {
    const std::vector<uint8_t> source{
        17, 33, 99, 210, 111, 2, 8, 254, 127,
    };
    const std::vector<uint8_t> expected{
        93, 55,  60, 93, 55,  60, 93, 55,  60, 93, 55,  60,
        86, 207, 79, 86, 207, 79, 86, 207, 79, 86, 207, 79,
    };
    const auto actual = trtmc::sam2_hoi::resize_pillow_bicubic_rgb_u8(source.data(), 3, 1, 2, 4);
    check(actual == expected, "SAM2 HOI bicubic resize clamps single-column boundary");
}

void test_preprocess_image_normalizes_fixed_1024_tensor() {
    const std::vector<float> source{0.0F, 128.0F / 255.0F, 1.0F};
    const auto output = trtmc::sam2_hoi::preprocess_image(source.data(), 1, 1);
    const auto plane =
        static_cast<std::size_t>(trtmc::sam2_hoi::kImageSize) * trtmc::sam2_hoi::kImageSize;
    check(output.size() == 3U * plane, "SAM2 HOI preprocess fixed tensor shape");
    if (output.size() != 3U * plane) {
        return;
    }
    check_close(output.front(), (0.0F - 0.485F) / 0.229F, 1.0e-6F,
                "SAM2 HOI preprocess red normalization");
    check_close(output[plane], (128.0F / 255.0F - 0.456F) / 0.224F, 1.0e-6F,
                "SAM2 HOI preprocess green normalization");
    check_close(output[3U * plane - 1U], (1.0F - 0.406F) / 0.225F, 1.0e-6F,
                "SAM2 HOI preprocess blue normalization");
}

void test_float_to_u8_rounding_matches_lround_boundaries() {
    int mismatches = 0;
    int unsafe_float_plus_half_mismatches = 0;
    const auto check_value = [&](float value) {
        const float scaled = value * 255.0F;
        const auto expected = static_cast<uint8_t>(std::lround(scaled));
        const auto actual = trtmc::sam2_hoi::detail::round_unit_float_to_u8(value);
        mismatches += actual != expected ? 1 : 0;
        const auto unsafe = static_cast<uint8_t>(scaled + 0.5F);
        unsafe_float_plus_half_mismatches += unsafe != expected ? 1 : 0;
    };

    // Exhaust every uint8 code point and every half-way decision boundary,
    // including the eight adjacent representable float values on both sides.
    for (int32_t code = 0; code <= 255; ++code) {
        check_value(static_cast<float>(code) / 255.0F);
    }
    for (int32_t lower_code = 0; lower_code < 255; ++lower_code) {
        const float boundary = (static_cast<float>(lower_code) + 0.5F) / 255.0F;
        check_value(boundary);
        float below = boundary;
        float above = boundary;
        for (int32_t step = 0; step < 8; ++step) {
            below = std::nextafter(below, 0.0F);
            above = std::nextafter(above, 1.0F);
            check_value(below);
            check_value(above);
        }
    }
    // Cover the valid interval interior densely, independent of the JPEG
    // decoder's canonical uint8/255 values.
    for (int32_t code = 0; code <= 65535; ++code) {
        check_value(static_cast<float>(code) / 65535.0F);
    }

    check(mismatches == 0, "SAM2 HOI widened rounding matches lround boundaries");
    check(unsafe_float_plus_half_mismatches > 0,
          "SAM2 HOI rounding test requires widening before adding one half");
}

void test_hole_fill_uses_eight_connectivity_and_inclusive_area() {
    constexpr int32_t height = 9;
    constexpr int32_t width = 9;
    constexpr auto plane = static_cast<std::size_t>(height * width);
    std::vector<float> masks(3U * plane, 1.0F);
    for (int32_t diagonal = 0; diagonal < 8; ++diagonal) {
        masks[static_cast<std::size_t>(diagonal) * width + diagonal] = -1.0F;
    }
    masks[0] = 0.0F;
    for (int32_t diagonal = 0; diagonal < 9; ++diagonal) {
        masks[plane + static_cast<std::size_t>(diagonal) * width + diagonal] = -2.0F;
    }
    std::fill(masks.begin() + static_cast<std::ptrdiff_t>(2U * plane), masks.end(), -3.0F);
    masks[2U * plane + 4U * width + 4U] = 0.25F;

    trtmc::sam2_hoi::fill_small_mask_holes(masks, 3, height, width);

    for (int32_t diagonal = 0; diagonal < 8; ++diagonal) {
        check_close(masks[static_cast<std::size_t>(diagonal) * width + diagonal], 0.1F, 0.0F,
                    "SAM2 HOI area-eight background component is filled");
    }
    for (int32_t diagonal = 0; diagonal < 9; ++diagonal) {
        check_close(masks[plane + static_cast<std::size_t>(diagonal) * width + diagonal], -2.0F,
                    0.0F, "SAM2 HOI diagonal area-nine component is not filled");
    }
    check_close(masks[2U * plane + 4U * width + 4U], 0.25F, 0.0F,
                "SAM2 HOI isolated foreground component remains untouched");
    check_close(masks[2U * plane], -3.0F, 0.0F,
                "SAM2 HOI large enclosing background remains untouched");
}

void test_mask_resize_align_corners_false_and_strict_threshold() {
    const std::vector<float> checkerboard{
        -1.0F,
        1.0F,
        1.0F,
        -1.0F,
    };
    const std::vector<uint8_t> expected{
        0, 0, 1, 0, 0, 0, 1, 0, 0,
    };
    const auto resized =
        trtmc::sam2_hoi::resize_and_threshold_masks(checkerboard.data(), 1, 2, 2, 3, 3);
    check(resized == expected, "SAM2 HOI mask resize uses align_corners=false boundaries");

    const float threshold = 0.01F;
    const std::vector<float> boundary{
        threshold,
        std::nextafter(threshold, std::numeric_limits<float>::infinity()),
        0.011F,
    };
    const auto strict =
        trtmc::sam2_hoi::resize_and_threshold_masks(boundary.data(), 1, 1, 3, 1, 3, threshold);
    check(strict == std::vector<uint8_t>({0, 1, 1}),
          "SAM2 HOI mask threshold comparison is strict");
}

void test_empty_mask_batch_is_valid() {
    std::vector<float> empty_logits;
    trtmc::sam2_hoi::fill_small_mask_holes(empty_logits, 0, 256, 256);
    check(empty_logits.empty(), "SAM2 HOI empty mask fill is a no-op");
    const auto empty_binary =
        trtmc::sam2_hoi::resize_and_threshold_masks(nullptr, 0, 256, 256, 7, 9);
    check(empty_binary.empty(), "SAM2 HOI empty mask resize is valid");

    const std::string path = "/tmp/trtmc_sam2_hoi_empty_io_test.npy";
    std::string error;
    check(trtmc::sam2_hoi::write_uint8_npy(path, {}, 0, 7, 9, &error),
          "SAM2 HOI empty NumPy mask batch is valid");
    std::ifstream input(path, std::ios::binary);
    const std::vector<uint8_t> bytes{std::istreambuf_iterator<char>(input),
                                     std::istreambuf_iterator<char>()};
    check(bytes.size() >= 10U, "SAM2 HOI empty NumPy preamble");
    if (bytes.size() >= 10U) {
        const auto header_size =
            static_cast<std::size_t>(bytes[8]) | (static_cast<std::size_t>(bytes[9]) << 8U);
        if (10U + header_size <= bytes.size()) {
            const std::string header(bytes.begin() + 10, bytes.begin() + 10 + header_size);
            check(header.find("'shape': (0, 1, 7, 9)") != std::string::npos,
                  "SAM2 HOI empty NumPy shape header");
            check(10U + header_size == bytes.size(), "SAM2 HOI empty NumPy payload");
        }
    }
    (void)std::remove(path.c_str());
}

void test_numpy_writer_header_shape_and_payload() {
    const std::string path = "/tmp/trtmc_sam2_hoi_io_test.npy";
    const std::vector<uint8_t> masks{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
    std::string error;
    check(trtmc::sam2_hoi::write_uint8_npy(path, masks, 2, 2, 3, &error),
          "SAM2 HOI NumPy writer succeeds");
    check(error.empty(), "SAM2 HOI NumPy writer leaves no error");

    std::ifstream input(path, std::ios::binary);
    const std::vector<uint8_t> bytes{std::istreambuf_iterator<char>(input),
                                     std::istreambuf_iterator<char>()};
    check(bytes.size() >= 10U + masks.size(), "SAM2 HOI NumPy output has preamble and payload");
    if (bytes.size() >= 10U + masks.size()) {
        const std::vector<uint8_t> expected_magic{0x93, 'N', 'U', 'M', 'P', 'Y', 1, 0};
        check(std::vector<uint8_t>(bytes.begin(), bytes.begin() + 8) == expected_magic,
              "SAM2 HOI NumPy v1.0 magic");
        const auto header_size =
            static_cast<std::size_t>(bytes[8]) | (static_cast<std::size_t>(bytes[9]) << 8U);
        check((10U + header_size) % 64U == 0U, "SAM2 HOI NumPy header alignment");
        check(10U + header_size + masks.size() == bytes.size(), "SAM2 HOI NumPy payload size");
        if (10U + header_size <= bytes.size()) {
            const std::string header(bytes.begin() + 10, bytes.begin() + 10 + header_size);
            check(header.find("'descr': '|u1'") != std::string::npos,
                  "SAM2 HOI NumPy dtype header");
            check(header.find("'fortran_order': False") != std::string::npos,
                  "SAM2 HOI NumPy row-major header");
            check(header.find("'shape': (2, 1, 2, 3)") != std::string::npos,
                  "SAM2 HOI NumPy four-dimensional shape header");
            check(std::vector<uint8_t>(bytes.begin() + 10 + header_size, bytes.end()) == masks,
                  "SAM2 HOI NumPy payload bytes");
        }
    }
    (void)std::remove(path.c_str());
}

} // namespace

int main() {
    test_bicubic_resize_matches_pillow_rgb_golden();
    test_bicubic_resize_matches_pillow_single_column_boundary();
    test_preprocess_image_normalizes_fixed_1024_tensor();
    test_float_to_u8_rounding_matches_lround_boundaries();
    test_hole_fill_uses_eight_connectivity_and_inclusive_area();
    test_mask_resize_align_corners_false_and_strict_threshold();
    test_empty_mask_batch_is_valid();
    test_numpy_writer_header_shape_and_payload();

    if (g_failures != 0) {
        std::cerr << g_failures << " SAM2 HOI I/O test(s) failed\n";
        return 1;
    }
    std::cout << "SAM2 HOI I/O tests passed\n";
    return 0;
}
