id = "mixtral"
plugin = "mixtral"
module = "plugin"
capabilities = ["disable_dual_profile_decoder"]
aliases = [
  "mixtral",
]
prefixes = [
  "mixtral",
]
debug_runner = "debug_runner.py|runner_from_bundle"
debug_runtime_strategies = [
  "mixtral_decoder_moe",
]
