# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "electra"
plugin = "electra"
module = "plugin"
aliases = [
  "electra",
]
prefixes = [
  "electra",
]
