id = "ltx_video"
plugin = "ltx_video"
module = "plugin"
aliases = [
  "ltx",
  "ltx-video",
  "ltx_video",
  "ltxpipeline",
  "ltxvideo",
]
prefixes = [
  "ltx_video",
]
diffusion_pipeline_classes = [
  "LTXPipeline",
]
