# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "patchtst"
plugin = "patchtst"
module = "plugin"
aliases = [
  "patchtst",
]
prefixes = [
  "patchtst",
]
