id = "fnet"
runtime_library = "libtrtmc_model_fnet.so"
runtime_plugins = ["plugin.cpp|register_fnet_plugin"]
runtime_strategies = ["fnet_encoder_only"]
runtime_tests = [
  "test_fnet_encoder_pipeline|test_fnet_encoder_pipeline.cpp|trtmc_model_fnet,trtmc_backend_trt|_|REQUIRES_TRT",
]
