id = "stablelm"
runtime_library = "libtrtmc_model_stablelm.so"
runtime_plugins = ["plugin.cpp|register_stablelm_plugin"]
runtime_strategies = ["stablelm_decoder_kv_cache"]
[validation_profiles]
decoder_debug = ["stablelm_decoder_kv_cache"]
