# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "internvl"
plugin = "internvl"
module = "plugin"
aliases = [
  "internvl",
  "internvl3",
  "internvl_chat",
]
prefixes = [
  "internvl",
]
