# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "roberta"
plugin = "roberta"
module = "plugin"
aliases = [
  "camembert",
  "roberta",
  "xlm-roberta",
]
prefixes = [
  "roberta",
]
