# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "dinov3"
runtime_library = "libtrtmc_model_dinov3.so"
runtime_plugins = ["plugin.cpp|register_dinov3_plugin"]
runtime_strategies = ["dinov3_image_feature_extraction"]
runtime_tests = [
  "test_dinov3_image_preprocess|test_dinov3_image_preprocess.cpp|trtmc_model_dinov3|_|_",
  "test_dinov3_pipeline|test_dinov3_pipeline.cpp|trtmc_model_dinov3|_|_",
]
