# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "timm_mobilenetv2"
plugin = "timm_mobilenetv2"
module = "plugin"
python_profile_specs = [
  "timm_mobilenetv2_reference|families/timm_mobilenetv2/python_profile_requirements/timm_mobilenetv2_reference.lock.txt|families/timm_mobilenetv2/python_profile_verify.py|true",
]
default_execution_profiles = [
  "reference|timm_mobilenetv2_reference",
]
aliases = [
  "timm_mobilenetv2",
  "mobilenetv2",
  "mobilenetv2_100",
]
prefixes = [
  "timm_mobilenetv2",
  "mobilenetv2",
]
