# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "bart"
aliases = [
  "bart",
  "mbart",
]
prefixes = [
  "bart",
]
debug_runner = "debug_runner.py|runner_from_bundle"
debug_runtime_strategies = [
  "bart_seq2seq_encoder_decoder",
]
