# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "timm_repvgg"
plugin = "timm_repvgg"
module = "plugin"
python_profile_specs = [
  "timm_repvgg_reference|families/timm_repvgg/python_profile_requirements/timm_repvgg_reference.lock.txt|families/timm_repvgg/python_profile_verify.py|true",
]
default_execution_profiles = [
  "reference|timm_repvgg_reference",
]
aliases = [
  "timm_repvgg",
  "repvgg",
  "repvgg_a2",
]
prefixes = [
  "timm_repvgg",
  "repvgg",
]
