# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "timm_regnet"
runtime_library = "libtrtmc_model_timm_regnet.so"
runtime_plugins = ["plugin.cpp|register_timm_regnet_plugin"]
runtime_strategies = ["timm_regnet_image_classification"]
runtime_tests = [
  "test_timm_regnet_image_preprocess_seam|test_timm_regnet_image_preprocess_seam.cpp|trtmc_model_timm_regnet|_|_",
]
