# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "whisper"
plugin = "whisper"
module = "plugin"
aliases = [
  "whisper",
]
prefixes = [
  "whisper",
]
