# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Run without a GPU or CUDA SDK: cmake -P cmake/edgellm/tests/package_contract.cmake
cmake_minimum_required(VERSION 3.20)
get_filename_component(_templates "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(_module "${_templates}/../EdgeLLM.cmake" ABSOLUTE)
if(NOT DEFINED TEST_ROOT)
  set(TEST_ROOT "/tmp/trtmc-edgellm-cmake-contract")
endif()
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}/package/lib/cmake/EdgeLLM" "${TEST_ROOT}/sdk/include"
  "${TEST_ROOT}/sdk/lib" "${TEST_ROOT}/modules" "${TEST_ROOT}/bin" "${TEST_ROOT}/source"
  "${TEST_ROOT}/package/include/edgellm/cpp" "${TEST_ROOT}/package/include/edgellm/3rdParty/nlohmannJson/include"
  "${TEST_ROOT}/package/include/edgellm/3rdParty/stb" "${TEST_ROOT}/package/include/edgellm/3rdParty/miniaudio")
set(_edge_version "0.10.1")
set(_edge_revision "e8b29522938901f6df19ebeedd4b69bc8edbcd97")
set(_edge_trt_version "11.1.0.106")
set(CUDAToolkit_VERSION "13.3.73")
set(CUDAToolkit_VERSION_MAJOR 13)
set(CUDAToolkit_VERSION_MINOR 3)
cmake_host_system_information(RESULT CMAKE_SYSTEM_PROCESSOR QUERY OS_PLATFORM)
set(TRTMC_EDGELLM_CUDA_ARCHITECTURE 80)
set(TRTMC_EDGELLM_TRT_ROOT "${TEST_ROOT}/sdk")
configure_file("${_templates}/EdgeLLMConfig.cmake.in" "${TEST_ROOT}/package/lib/cmake/EdgeLLM/EdgeLLMConfig.cmake" @ONLY)
configure_file("${_templates}/CheckNative.cmake" "${TEST_ROOT}/package/lib/cmake/EdgeLLM/CheckNative.cmake" COPYONLY)
include(CMakePackageConfigHelpers)
write_basic_package_version_file("${TEST_ROOT}/package/lib/cmake/EdgeLLM/EdgeLLMConfigVersion.cmake"
  VERSION "${_edge_version}" COMPATIBILITY ExactVersion ARCH_INDEPENDENT)
file(WRITE "${TEST_ROOT}/sdk/include/NvInfer.h" "// test fixture\n")
file(WRITE "${TEST_ROOT}/sdk/include/NvInferVersion.h" "#define ENTERPRISE_MAJOR 11\n#define NV_TENSORRT_MAJOR ENTERPRISE_MAJOR\n#define NV_TENSORRT_MINOR 1\n#define NV_TENSORRT_PATCH 0\n#define NV_TENSORRT_BUILD 106\n")
foreach(_library IN ITEMS nvinfer nvonnxparser)
  file(WRITE "${TEST_ROOT}/sdk/lib/lib${_library}.so" "fixture")
endforeach()
file(WRITE "${TEST_ROOT}/modules/FindCUDAToolkit.cmake" [=[
set(CUDAToolkit_FOUND TRUE)
set(CUDAToolkit_VERSION_MAJOR "${TEST_CUDA_MAJOR}")
set(CUDAToolkit_VERSION_MINOR 3)
add_library(CUDA::cudart INTERFACE IMPORTED)
add_library(CUDA::cuda_driver INTERFACE IMPORTED)
]=])
file(WRITE "${TEST_ROOT}/modules/FindThreads.cmake" "set(Threads_FOUND TRUE)\nadd_library(Threads::Threads INTERFACE IMPORTED)\n")
file(WRITE "${TEST_ROOT}/modules/Findnlohmann_json.cmake" "set(nlohmann_json_FOUND TRUE)\n")
file(WRITE "${TEST_ROOT}/bin/nvidia-smi" [=[#!/bin/sh
echo "$TEST_GPU_CAP"
]=])
file(CHMOD "${TEST_ROOT}/bin/nvidia-smi" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
set(ENV{PATH} "${TEST_ROOT}/bin:$ENV{PATH}")
set(ENV{TRT_ROOT} "${TEST_ROOT}/sdk")
set(ENV{TEST_GPU_CAP} "8.0")
file(WRITE "${TEST_ROOT}/source/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(package_contract LANGUAGES CXX)\nset(_version unrelated_caller_value)\ninclude(GNUInstallDirs)\nlist(PREPEND CMAKE_MODULE_PATH \"${TEST_ROOT}/modules\")\nset(EdgeLLM_DIR \"${TEST_ROOT}/package/lib/cmake/EdgeLLM\")\nif(TEST_OFF)\n  set(TRTMC_ENABLE_EDGELLM OFF)\n  include(\"${_module}\")\n  if(TARGET EdgeLLM::Core OR TARGET trtmc_edgellm_dependency)\n    message(FATAL_ERROR \"Optional-off configuration acquired Edge\")\n  endif()\nelse()\n  set(TRTMC_ENABLE_EDGELLM ON)\n  include(\"${_module}\")\n  if(NOT TARGET EdgeLLM::Core OR TARGET trtmc_edgellm_dependency)\n    message(FATAL_ERROR \"Installed package was not reused\")\n  endif()\nendif()\n")
# Each negative case must fail for its intended reason, not an incidental fixture error.
function(check name expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_ROOT}/source" -B "${TEST_ROOT}/${name}"
    -DTEST_CUDA_MAJOR=13 ${ARGN} RESULT_VARIABLE _status OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
  file(WRITE "${TEST_ROOT}/${name}.log" "${_stdout}${_stderr}")
  if(expected STREQUAL "PASS")
    if(NOT _status EQUAL 0)
      message(FATAL_ERROR "${name} failed: ${_stdout}${_stderr}")
    endif()
  elseif(_status EQUAL 0 OR NOT "${_stdout}${_stderr}" MATCHES "${expected}")
    message(FATAL_ERROR "${name} did not reject with : ${_stdout}${_stderr}")
  endif()
  message(STATUS "PASS ${name}")
endfunction()
check(optional_off PASS -DTEST_OFF=ON)
check(installed_native PASS)
check(wrong_cuda "requires the CUDA SDK" -DTEST_CUDA_MAJOR=12)
check(cross_compile "cross compilation is not supported" -DCMAKE_SYSTEM_NAME=Linux)
set(ENV{TEST_GPU_CAP} "9.0")
check(wrong_gpu "requires a local GPU")
set(ENV{TEST_GPU_CAP} "8.0")
file(APPEND "${TEST_ROOT}/sdk/include/NvInferVersion.h" "#undef NV_TENSORRT_BUILD\n#define NV_TENSORRT_BUILD 107\n")
check(wrong_trt_build "requires TensorRT 11.1.0.106")
file(APPEND "${TEST_ROOT}/sdk/include/NvInferVersion.h" "#undef NV_TENSORRT_BUILD\n#define NV_TENSORRT_BUILD 106\n")
file(APPEND "${TEST_ROOT}/package/lib/cmake/EdgeLLM/EdgeLLMConfig.cmake" "set(EdgeLLM_REVISION wrong)\n")
check(wrong_revision "does not match the pinned GitHub revision")
