# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "chronos_bolt"
runtime_library = "libtrtmc_model_chronos_bolt.so"
runtime_plugins = ["plugin.cpp|register_chronos_bolt_plugin"]
runtime_strategies = ["chronos_bolt_trt"]
task_strategy = "neural_operator"
