# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "glm"
runtime_library = "libtrtmc_model_glm.so"
runtime_plugins = ["plugin.cpp|register_glm_plugin"]
runtime_strategies = ["glm_decoder_kv_cache"]
runtime_tests = [
  "test_glm_native_kv_cache|test_glm_native_kv_cache.cpp|trtmc_model_glm,trtmc_backend_trt|_|REQUIRES_TRT,REQUIRES_GPU",
]
