# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "minimax_music3"
runtime_library = "libtrtmc_model_minimax_music3.so"
runtime_plugins = ["plugin.cpp|register_minimax_music3_plugin"]
runtime_config_schemas = ["config_schema.cpp|register_minimax_music3_schema"]
runtime_strategies = ["minimax_music3_text_to_music"]
