id = "distilbert"
runtime_library = "libtrtmc_model_distilbert.so"
runtime_plugins = ["plugin.cpp|register_distilbert_plugin"]
runtime_strategies = ["distilbert_encoder_only"]
runtime_tests = [
  "test_distilbert_encoder_pipeline|test_distilbert_encoder_pipeline.cpp|trtmc_model_distilbert,trtmc_backend_trt|_|REQUIRES_TRT",
]
