# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "marian"
runtime_library = "libtrtmc_model_marian.so"
runtime_plugins = ["plugin.cpp|register_marian_plugin"]
runtime_strategies = ["marian_translation"]
