# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Release-artifact tests for the SAM3 TensorRT-only runtime contract."""

from __future__ import annotations

import importlib.util
import json
import subprocess
import struct
import sys
from collections.abc import Callable, Sequence
from pathlib import Path

import pytest


_AUDITOR_PATH = Path(__file__).with_name("audit_runtime_contract.py")
_AUDITOR_SPEC = importlib.util.spec_from_file_location(
    "sam3_runtime_contract_auditor",
    _AUDITOR_PATH,
)
assert _AUDITOR_SPEC is not None
assert _AUDITOR_SPEC.loader is not None
audit = importlib.util.module_from_spec(_AUDITOR_SPEC)
sys.modules[_AUDITOR_SPEC.name] = audit
_AUDITOR_SPEC.loader.exec_module(audit)


def test_sam3_runtime_auditor_runs_directly_from_clean_checkout(tmp_path: Path) -> None:
    completed = subprocess.run(
        [sys.executable, "-I", "-S", str(_AUDITOR_PATH), "--help"],
        cwd=tmp_path,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )

    assert completed.returncode == 0, completed.stderr
    assert "Audit a production SAM3 bundle" in completed.stdout
    assert "--cmake-cache" in completed.stdout


def _valid_section_payloads() -> dict[str, bytes]:
    payloads = {
        name: (
            b"ftrt native TensorRT plan " + name.encode("ascii")
            if name in audit.SAM3_PLAN_SECTIONS
            else b"{}"
        )
        for name in sorted(audit.SAM3_BUNDLE_SECTIONS)
    }
    payloads["config.json"] = json.dumps(
        {
            "detector_config": {"text_config": {"vocab_size": 3}},
            "sam3_video_tracking_supported": True,
        }
    ).encode()
    payloads["tokenizer.json"] = json.dumps(
        {
            "model": {
                "type": "BPE",
                "vocab": {"a": 0, "b": 1, "ab": 2},
                "merges": ["a b"],
            }
        }
    ).encode()
    return payloads


def _write_bundle(
    path: Path,
    *,
    section_payloads: dict[str, bytes] | None = None,
    runtime_strategy: str = "sam3_prompted_segmentation",
    model_type: str = "sam3_video",
    gap_before_section: str | None = None,
    gap_payload: bytes = b"",
    trailing_payload: bytes = b"",
    header_mutator: Callable[[bytes], bytes] | None = None,
) -> Path:
    payloads = _valid_section_payloads()
    if section_payloads is not None:
        payloads = dict(section_payloads)

    offset = 0
    section_table: dict[str, dict[str, int]] = {}
    payload_chunks: list[bytes] = []
    for name, payload in payloads.items():
        if name == gap_before_section:
            payload_chunks.append(gap_payload)
            offset += len(gap_payload)
        section_table[name] = {"offset": offset, "size": len(payload)}
        payload_chunks.append(payload)
        offset += len(payload)
    header = {
        "model_type": model_type,
        "runtime_strategy": runtime_strategy,
        "sections": section_table,
    }
    encoded_header = json.dumps(header).encode("utf-8")
    if header_mutator is not None:
        encoded_header = header_mutator(encoded_header)
    with path.open("wb") as handle:
        handle.write(b"BUNDLE\x01\x00")
        handle.write(struct.pack("<Q", len(encoded_header)))
        handle.write(encoded_header)
        for payload in payload_chunks:
            handle.write(payload)
        handle.write(trailing_payload)
    return path


def _write_runtime_dsos(tmp_path: Path) -> tuple[Path, Path, Path]:
    paths = (
        tmp_path / "libtrtmc_core.so",
        tmp_path / "libtrtmc_backend_trt.so",
        tmp_path / "libtrtmc_model_sam3.so",
    )
    for path in paths:
        path.write_bytes(b"\x7fELF" + path.name.encode("ascii"))
    return paths


def _valid_cmake_cache_text(
    *,
    cache_dir: str | Path = "/tmp/sam3-release-build",
    libtorch: str = "OFF",
    tvm_ffi: str = "OFF",
    include_tvm_ffi: bool = True,
    libtorch_type: str = "BOOL",
) -> str:
    cache_dir = Path(cache_dir)
    lines = [
        "# This is the CMakeCache file.",
        f"# For build in directory: {cache_dir}",
        "# It was generated by CMake: /usr/bin/cmake",
        "# KEY:TYPE=VALUE",
        "CMAKE_PROJECT_NAME:STATIC=tensorrt_model_connect",
        f"CMAKE_CACHEFILE_DIR:INTERNAL={cache_dir}",
        "CMAKE_HOME_DIRECTORY:INTERNAL=/src/TensorRT-Model-Connect",
        "CMAKE_GENERATOR:INTERNAL=Ninja",
        "CMAKE_COMMAND:INTERNAL=/usr/bin/cmake",
        "CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3",
        "CMAKE_CACHE_MINOR_VERSION:INTERNAL=30",
        "CMAKE_CACHE_PATCH_VERSION:INTERNAL=5",
        f"TRTMC_ENABLE_LIBTORCH_MULTINOMIAL:{libtorch_type}={libtorch}",
    ]
    if include_tvm_ffi:
        lines.append(f"TRTMC_ENABLE_TVM_FFI:BOOL={tvm_ffi}")
    return "\n".join(lines) + "\n"


class _FakeElfTools:
    def __init__(
        self,
        *,
        injected_output: dict[str | tuple[str, str], str] | None = None,
        backend_has_tensorrt: bool = True,
    ) -> None:
        self.injected_output = injected_output or {}
        self.backend_has_tensorrt = backend_has_tensorrt

    def __call__(self, command: Sequence[str], stdin: str | None) -> str:
        tool = command[0]
        path_key = (tool, Path(command[-1]).name) if len(command) > 1 else None
        injected = self.injected_output.get(path_key) if path_key is not None else None
        if injected is None:
            injected = self.injected_output.get(tool)
        if injected is not None:
            return injected
        if tool == "readelf":
            path = Path(command[-1])
            needed = ["libcudart.so.13", "libstdc++.so.6"]
            if path.name.startswith("libtrtmc_backend_trt") and self.backend_has_tensorrt:
                needed.append("libnvinfer.so.10")
            dynamic = [f"0x0000000000000001 (NEEDED) Shared library: [{name}]" for name in needed]
            if any(pattern.fullmatch(path.name) for pattern in audit._DSO_ROLE_PATTERNS.values()):
                dynamic.append(f"0x000000000000000e (SONAME) Library soname: [{path.name}]")
            return "\n".join(dynamic)
        if tool == "ldd":
            return "libcudart.so.13 => /usr/local/cuda/lib64/libcudart.so.13"
        if tool == "nm":
            name = Path(command[-1]).name
            if name.startswith("libtrtmc_backend_trt"):
                return "trtmc_create_backend\ntrtmc_backend_abi"
            if name.startswith("libtrtmc_model_sam3"):
                return "trtmc_sam3_video_create\ntrtmc_sam3_video_propagate"
            if name.startswith("libtrtmc_core"):
                return "trtmc::PipelineRegistry::instance()"
            return "trtmc_transitive_runtime_symbol"
        if tool == "c++filt":
            return stdin or ""
        if tool == "strings":
            return "TRTMC SAM3 native TensorRT runtime"
        raise AssertionError(f"Unexpected audit tool: {command!r}")


class _FakeProbeRunner:
    def __init__(
        self,
        dsos: tuple[Path, Path, Path],
        *,
        omitted_label: str | None = None,
        wrong_size_label: str | None = None,
        tracker_init_count: int = 3,
        mapped_role_override: tuple[str, Path] | None = None,
        extra_mapped_dsos: Sequence[Path] = (),
        extra_stderr: str = "",
    ) -> None:
        self.dsos = dsos
        self.omitted_label = omitted_label
        self.wrong_size_label = wrong_size_label
        self.tracker_init_count = tracker_init_count
        self.mapped_role_override = mapped_role_override
        self.extra_mapped_dsos = tuple(extra_mapped_dsos)
        self.extra_stderr = extra_stderr
        self.commands: list[tuple[str, ...]] = []

    def __call__(self, command: Sequence[str]) -> subprocess.CompletedProcess[str]:
        self.commands.append(tuple(command))
        role_paths = {
            "core": self.dsos[0],
            "tensorrt_backend": self.dsos[1],
            "sam3_model": self.dsos[2],
        }
        if self.mapped_role_override is not None:
            role, path = self.mapped_role_override
            role_paths[role] = path
        mapped_dsos = []
        for role, path in role_paths.items():
            canonical = path.resolve(strict=True)
            stat = canonical.stat()
            mapped_dsos.append(
                {
                    "role": role,
                    "path": str(canonical),
                    "device": stat.st_dev,
                    "inode": stat.st_ino,
                }
            )
        new_mapped_dsos = [
            {key: value for key, value in entry.items() if key != "role"} for entry in mapped_dsos
        ]
        for path in self.extra_mapped_dsos:
            canonical = path.resolve(strict=True)
            stat = canonical.stat()
            new_mapped_dsos.append(
                {
                    "path": str(canonical),
                    "device": stat.st_dev,
                    "inode": stat.st_ino,
                }
            )
        stdout = audit._NATIVE_PROBE_PREFIX + json.dumps(
            {"mapped_dsos": mapped_dsos, "new_mapped_dsos": new_mapped_dsos}
        )

        payloads = _valid_section_payloads()
        timing_lines: list[str] = []
        for section, label in audit._SAM3_PLAN_LOAD_LABELS.items():
            if label == self.omitted_label:
                continue
            count = self.tracker_init_count if section == "sam3_tracker_init_engine_plan" else 1
            size = len(payloads[section])
            if label == self.wrong_size_label:
                size += 1
            timing_lines.extend(
                f'[trtmc.load_timing] label="{label}" load_deserialize_ms=1.000000 '
                f"plan_bytes={size}"
                for _ in range(count)
            )
        return subprocess.CompletedProcess(
            args=list(command),
            returncode=0,
            stdout=stdout + "\n",
            stderr="\n".join(timing_lines + [self.extra_stderr]) + "\n",
        )


def test_sam3_runtime_artifact_audit_accepts_native_tensorrt_release(tmp_path: Path) -> None:
    bundle = _write_bundle(tmp_path / "sam3.bundle")
    dsos = _write_runtime_dsos(tmp_path)
    cache = tmp_path / "CMakeCache.txt"
    cache.write_text(_valid_cmake_cache_text(cache_dir=tmp_path), encoding="utf-8")
    probe_runner = _FakeProbeRunner(dsos)

    report = audit.audit_sam3_runtime_artifacts(
        bundle_path=bundle,
        dso_paths=dsos,
        cmake_cache=cache,
        tool_runner=_FakeElfTools(),
        probe_runner=probe_runner,
    )

    assert report.plan_count == 12
    assert report.live_load_succeeded is True
    assert set(report.bundle_sections) == audit.SAM3_BUNDLE_SECTIONS
    assert len(report.bundle_sha256) == 64
    assert len(report.cmake_cache_sha256) == 64
    assert set(report.dso_sha256) == {str(path) for path in dsos}
    assert all(len(digest) == 64 for digest in report.dso_sha256.values())
    assert len(probe_runner.commands) == 1
    command = probe_runner.commands[0]
    assert command[1:3] == ("-I", "-S")
    assert command[command.index("--core-dso") + 1] == str(dsos[0])
    assert command[command.index("--backend-dso") + 1] == str(dsos[1])
    assert command[command.index("--model-dso") + 1] == str(dsos[2])


def test_sam3_runtime_artifact_audit_binds_dsos_to_cmake_build_tree(tmp_path: Path) -> None:
    bundle = _write_bundle(tmp_path / "sam3.bundle")
    dsos = _write_runtime_dsos(tmp_path)
    build_dir = tmp_path / "build"
    build_dir.mkdir()
    cache = build_dir / "CMakeCache.txt"
    cache.write_text(_valid_cmake_cache_text(cache_dir=build_dir), encoding="utf-8")

    with pytest.raises(audit.Sam3RuntimeContractError, match="not from the CMake build tree"):
        audit.audit_sam3_runtime_artifacts(
            bundle_path=bundle,
            dso_paths=dsos,
            cmake_cache=cache,
            tool_runner=_FakeElfTools(),
            probe_runner=_FakeProbeRunner(dsos),
        )


def test_sam3_bundle_audit_requires_exact_native_plan_and_asset_sections(tmp_path: Path) -> None:
    payloads = _valid_section_payloads()
    payloads["tracker_aoti.pt2"] = b"PK\x03\x04"
    bundle = _write_bundle(tmp_path / "sam3-extra.bundle", section_payloads=payloads)

    with pytest.raises(audit.Sam3RuntimeContractError, match="unexpected=.*tracker_aoti.pt2"):
        audit.audit_sam3_bundle(bundle)


def test_sam3_bundle_audit_rejects_duplicate_header_key(tmp_path: Path) -> None:
    def duplicate_model_type(encoded: bytes) -> bytes:
        return encoded.replace(
            b'"model_type": "sam3_video"',
            b'"model_type": "sam3_video", "model_type": "sam3"',
            1,
        )

    bundle = _write_bundle(
        tmp_path / "sam3-duplicate-header.bundle",
        header_mutator=duplicate_model_type,
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="duplicate JSON object key"):
        audit.audit_sam3_bundle(bundle)


def test_sam3_bundle_audit_rejects_duplicate_json_asset_key(tmp_path: Path) -> None:
    payloads = _valid_section_payloads()
    payloads["config.json"] = (
        b'{"detector_config":{"text_config":{"vocab_size":3,"vocab_size":4}},'
        b'"sam3_video_tracking_supported":true}'
    )
    bundle = _write_bundle(tmp_path / "sam3-duplicate-asset.bundle", section_payloads=payloads)

    with pytest.raises(audit.Sam3RuntimeContractError, match="duplicate JSON object key"):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize("payload_location", ["gap", "trailing"])
def test_sam3_bundle_audit_rejects_unaccounted_payload_bytes(
    tmp_path: Path,
    payload_location: str,
) -> None:
    kwargs = (
        {
            "gap_before_section": "sam3_tracker_step_engine_plan",
            "gap_payload": b"hidden-aoti-package",
        }
        if payload_location == "gap"
        else {"trailing_payload": b"hidden-aoti-package"}
    )
    bundle = _write_bundle(tmp_path / f"sam3-{payload_location}.bundle", **kwargs)

    with pytest.raises(audit.Sam3RuntimeContractError, match="unaccounted payload bytes"):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize("payload", [b"PK\x03\x04aoti", b"not-an-engine", b"onnx-protobuf"])
def test_sam3_bundle_audit_rejects_non_tensorrt_plan_payload(
    tmp_path: Path,
    payload: bytes,
) -> None:
    payloads = _valid_section_payloads()
    payloads["sam3_tracker_step_engine_plan"] = payload
    bundle = _write_bundle(tmp_path / "sam3-bad-plan.bundle", section_payloads=payloads)

    with pytest.raises(audit.Sam3RuntimeContractError, match="not a serialized TensorRT plan"):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize(
    "marker",
    [
        b"AOTInductorModelContainer",
        b"TvmFfiKernel",
        b"libtorch.so",
        b"libpython3.12.so",
        b"onnxruntime",
        b"tracker.pt2",
    ],
)
def test_sam3_bundle_audit_rejects_bridge_marker_inside_plan(
    tmp_path: Path,
    marker: bytes,
) -> None:
    payloads = _valid_section_payloads()
    payloads["sam3_tracker_step_engine_plan"] = b"ftrt" + marker
    bundle = _write_bundle(tmp_path / "sam3-bridge-plan.bundle", section_payloads=payloads)

    with pytest.raises(audit.Sam3RuntimeContractError, match="forbidden marker"):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize(
    "marker",
    [
        b"AOTInductorModelContainer",
        b"TvmFfiKernel",
        b"libtorch.so",
        b"libpython3.12.so",
        b"onnxruntime",
        b"tracker.pt2",
    ],
)
def test_sam3_bundle_audit_rejects_bridge_marker_inside_asset(
    tmp_path: Path,
    marker: bytes,
) -> None:
    payloads = _valid_section_payloads()
    payloads["config.json"] = b'{"hidden_runtime": "' + marker + b'"}'
    bundle = _write_bundle(tmp_path / "sam3-bridge-asset.bundle", section_payloads=payloads)

    with pytest.raises(audit.Sam3RuntimeContractError, match="forbidden marker"):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize(
    ("asset", "payload", "message"),
    [
        ("config.json", b"not-json", "not valid JSON"),
        ("tokenizer.json", b"[]", "must contain an object"),
        ("merges.txt", b"\xff", "not valid UTF-8"),
        ("merges.txt", b"version\x00payload", "binary NUL"),
    ],
)
def test_sam3_bundle_audit_rejects_malformed_asset_payload(
    tmp_path: Path,
    asset: str,
    payload: bytes,
    message: str,
) -> None:
    payloads = _valid_section_payloads()
    payloads[asset] = payload
    bundle = _write_bundle(tmp_path / "sam3-malformed-asset.bundle", section_payloads=payloads)

    with pytest.raises(audit.Sam3RuntimeContractError, match=message):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize("value", [False, "true", 1, None])
def test_sam3_bundle_audit_requires_video_tracking_live_load(
    tmp_path: Path,
    value: object,
) -> None:
    payloads = _valid_section_payloads()
    payloads["config.json"] = json.dumps(
        {
            "detector_config": {"text_config": {"vocab_size": 3}},
            "sam3_video_tracking_supported": value,
        }
    ).encode()
    bundle = _write_bundle(tmp_path / "sam3-no-video-tracking.bundle", section_payloads=payloads)

    with pytest.raises(
        audit.Sam3RuntimeContractError,
        match="sam3_video_tracking_supported to JSON true",
    ):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize(
    ("vocab", "merges", "message"),
    [
        ({"a": 0, "b": 2}, ["a b"], "unique and dense"),
        ({"a": 0, "b": 1, "ab": 2}, ["not-a-pair"], "invalid BPE merge"),
    ],
)
def test_sam3_bundle_audit_rejects_unusable_native_bpe_tokenizer(
    tmp_path: Path,
    vocab: dict[str, int],
    merges: list[str],
    message: str,
) -> None:
    payloads = _valid_section_payloads()
    payloads["tokenizer.json"] = json.dumps(
        {"model": {"type": "BPE", "vocab": vocab, "merges": merges}}
    ).encode()
    bundle = _write_bundle(tmp_path / "sam3-invalid-bpe.bundle", section_payloads=payloads)

    with pytest.raises(audit.Sam3RuntimeContractError, match=message):
        audit.audit_sam3_bundle(bundle)


@pytest.mark.parametrize(
    "cache_kwargs",
    [
        {"libtorch": "ON"},
        {"tvm_ffi": "ON"},
        {"include_tvm_ffi": False},
        {"libtorch_type": "STRING"},
    ],
)
def test_sam3_build_cache_audit_rejects_enabled_or_missing_bridges(
    tmp_path: Path,
    cache_kwargs: dict[str, object],
) -> None:
    cache = tmp_path / "CMakeCache.txt"
    cache.write_text(
        _valid_cmake_cache_text(cache_dir=tmp_path, **cache_kwargs),
        encoding="utf-8",
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="must be OFF"):
        audit.audit_sam3_build_cache(cache)


def test_sam3_build_cache_audit_rejects_two_spoofed_option_lines(tmp_path: Path) -> None:
    cache = tmp_path / "CMakeCache.txt"
    cache.write_text(
        "TRTMC_ENABLE_LIBTORCH_MULTINOMIAL:BOOL=OFF\nTRTMC_ENABLE_TVM_FFI:BOOL=OFF\n",
        encoding="utf-8",
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="Not a generated CMakeCache"):
        audit.audit_sam3_build_cache(cache)


def test_sam3_build_cache_audit_rejects_duplicate_cache_key(tmp_path: Path) -> None:
    cache = tmp_path / "CMakeCache.txt"
    cache.write_text(
        _valid_cmake_cache_text(cache_dir=tmp_path)
        + "TRTMC_ENABLE_LIBTORCH_MULTINOMIAL:BOOL=OFF\n",
        encoding="utf-8",
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="Duplicate CMake cache entry"):
        audit.audit_sam3_build_cache(cache)


def test_sam3_build_cache_audit_binds_declared_build_directory(tmp_path: Path) -> None:
    cache = tmp_path / "CMakeCache.txt"
    other_build_dir = tmp_path / "other-build"
    other_build_dir.mkdir()
    cache.write_text(
        _valid_cmake_cache_text(cache_dir=other_build_dir),
        encoding="utf-8",
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="CMAKE_CACHEFILE_DIR does not match"):
        audit.audit_sam3_build_cache(cache)


@pytest.mark.parametrize(
    ("tool", "marker"),
    [
        ("readelf", "Shared library: [libtorch.so]"),
        ("readelf", "Shared library: [libc10.so]"),
        ("readelf", "Shared library: [libpython3.12.so]"),
        ("ldd", "libonnxruntime.so => /runtime/libonnxruntime.so"),
        ("c++filt", "torch::Tensor tracker_step"),
        ("c++filt", "c10::Tensor tracker_step"),
        ("c++filt", "at::Tensor tracker_step"),
        ("c++filt", "PyObject_Call tracker_step"),
        ("c++filt", "_Py_Dealloc tracker_step"),
        ("strings", "AOTI runtime package"),
        ("strings", "TvmFfiKernel"),
        ("c++filt", "tvm::ffi::Function tracker_step"),
    ],
)
def test_sam3_runtime_dependency_audit_rejects_external_frameworks(
    tmp_path: Path,
    tool: str,
    marker: str,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    runner = _FakeElfTools(injected_output={tool: marker})

    with pytest.raises(audit.Sam3RuntimeContractError, match="Forbidden runtime dependency"):
        audit.audit_sam3_runtime_dependencies(dsos, tool_runner=runner)


def test_sam3_runtime_dependency_audit_rejects_unresolved_library(tmp_path: Path) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    runner = _FakeElfTools(injected_output={"ldd": "libcuda.so.1 => not found"})

    with pytest.raises(audit.Sam3RuntimeContractError, match="unresolved library"):
        audit.audit_sam3_runtime_dependencies(dsos, tool_runner=runner)


def test_sam3_runtime_dependency_audit_rejects_required_roles_sharing_one_elf(
    tmp_path: Path,
) -> None:
    shared = tmp_path / "shared-runtime.so"
    shared.write_bytes(b"\x7fELFshared")
    dsos = (
        tmp_path / "libtrtmc_core.so",
        tmp_path / "libtrtmc_backend_trt.so",
        tmp_path / "libtrtmc_model_sam3.so",
    )
    for path in dsos:
        path.symlink_to(shared)

    with pytest.raises(audit.Sam3RuntimeContractError, match="resolve to the same ELF file"):
        audit.audit_sam3_runtime_dependencies(dsos, tool_runner=_FakeElfTools())


def test_sam3_runtime_dependency_audit_requires_role_soname(tmp_path: Path) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    runner = _FakeElfTools(
        injected_output={
            ("readelf", "libtrtmc_model_sam3.so"): (
                "0x1 (NEEDED) Shared library: [libcudart.so.13]\n"
                "0xe (SONAME) Library soname: [libtrtmc_core.so]"
            )
        }
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="expected 'sam3_model' SONAME"):
        audit.audit_sam3_runtime_dependencies(dsos, tool_runner=runner)


def test_sam3_runtime_dependency_audit_requires_role_symbols(tmp_path: Path) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    runner = _FakeElfTools(injected_output={("nm", "libtrtmc_model_sam3.so"): "unrelated_symbol"})

    with pytest.raises(audit.Sam3RuntimeContractError, match="missing required 'sam3_model'"):
        audit.audit_sam3_runtime_dependencies(dsos, tool_runner=runner)


def test_sam3_runtime_dependency_audit_scans_transitive_model_connect_dso(
    tmp_path: Path,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    transitive = tmp_path / "libtrtmc_tracker_bridge.so"
    transitive.write_bytes(b"\x7fELFtransitive")
    runner = _FakeElfTools(
        injected_output={
            (
                "ldd",
                "libtrtmc_model_sam3.so",
            ): f"libtrtmc_tracker_bridge.so => {transitive} (0x0000000000010000)",
            ("strings", transitive.name): "AOTI runtime package",
        }
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="Forbidden runtime dependency"):
        audit.audit_sam3_runtime_dependencies(dsos, tool_runner=runner)


def test_sam3_runtime_dependency_audit_rejects_non_tensorrt_framework(
    tmp_path: Path,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    runner = _FakeElfTools(
        injected_output={
            "ldd": "libtensorflow.so.2 => /runtime/libtensorflow.so.2",
        }
    )

    with pytest.raises(audit.Sam3RuntimeContractError, match="Non-TensorRT runtime libraries"):
        audit.audit_sam3_runtime_dependencies(dsos, tool_runner=runner)


def test_sam3_runtime_dependency_audit_requires_backend_link_to_tensorrt(
    tmp_path: Path,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)

    with pytest.raises(audit.Sam3RuntimeContractError, match="does not depend on libnvinfer"):
        audit.audit_sam3_runtime_dependencies(
            dsos,
            tool_runner=_FakeElfTools(backend_has_tensorrt=False),
        )


@pytest.mark.parametrize(
    ("runner_kwargs", "message"),
    [
        (
            {"omitted_label": "sam3 tracker_memory_engine"},
            "did not prove plan section 'sam3_tracker_memory_engine_plan'",
        ),
        (
            {"wrong_size_label": "sam3 tracker_step_engine"},
            "size mismatch for plan section 'sam3_tracker_step_engine_plan'",
        ),
    ],
)
def test_sam3_native_live_load_requires_every_plan_and_exact_size(
    tmp_path: Path,
    runner_kwargs: dict[str, object],
    message: str,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    roles = audit._require_dso_roles(dsos)
    plan_sizes = {
        name: len(payload)
        for name, payload in _valid_section_payloads().items()
        if name in audit.SAM3_PLAN_SECTIONS
    }

    with pytest.raises(audit.Sam3RuntimeContractError, match=message):
        audit._audit_native_live_load(
            tmp_path / "sam3.bundle",
            roles,
            plan_sizes,
            probe_runner=_FakeProbeRunner(dsos, **runner_kwargs),
        )


def test_sam3_native_live_load_accepts_one_tracker_init_deserialize_record(
    tmp_path: Path,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    roles = audit._require_dso_roles(dsos)
    plan_sizes = {
        name: len(payload)
        for name, payload in _valid_section_payloads().items()
        if name in audit.SAM3_PLAN_SECTIONS
    }

    audit._audit_native_live_load(
        tmp_path / "sam3.bundle",
        roles,
        plan_sizes,
        probe_runner=_FakeProbeRunner(dsos, tracker_init_count=1),
    )


def test_sam3_native_live_load_rejects_missing_optional_tracker_init_module(
    tmp_path: Path,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    roles = audit._require_dso_roles(dsos)
    plan_sizes = {
        name: len(payload)
        for name, payload in _valid_section_payloads().items()
        if name in audit.SAM3_PLAN_SECTIONS
    }

    with pytest.raises(audit.Sam3RuntimeContractError, match="without a usable tracker-init"):
        audit._audit_native_live_load(
            tmp_path / "sam3.bundle",
            roles,
            plan_sizes,
            probe_runner=_FakeProbeRunner(
                dsos,
                tracker_init_count=1,
                extra_stderr=(
                    "[trtmc] WARNING: failed to load optional engine: sam3 tracker_init_engine"
                ),
            ),
        )


def test_sam3_native_live_load_requires_exact_mapped_dso_identities(tmp_path: Path) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    wrong_backend = tmp_path / "unrequested-backend.so"
    wrong_backend.write_bytes(b"\x7fELFwrong")
    roles = audit._require_dso_roles(dsos)
    plan_sizes = {
        name: len(payload)
        for name, payload in _valid_section_payloads().items()
        if name in audit.SAM3_PLAN_SECTIONS
    }

    with pytest.raises(audit.Sam3RuntimeContractError, match="did not map exactly"):
        audit._audit_native_live_load(
            tmp_path / "sam3.bundle",
            roles,
            plan_sizes,
            probe_runner=_FakeProbeRunner(
                dsos,
                mapped_role_override=("tensorrt_backend", wrong_backend),
            ),
        )


def test_sam3_native_live_load_rejects_forbidden_mapping_delta(tmp_path: Path) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    forbidden_dso = tmp_path / "libtorch.so"
    forbidden_dso.write_bytes(b"\x7fELFforbidden")
    roles = audit._require_dso_roles(dsos)
    plan_sizes = {
        name: len(payload)
        for name, payload in _valid_section_payloads().items()
        if name in audit.SAM3_PLAN_SECTIONS
    }

    with pytest.raises(audit.Sam3RuntimeContractError, match="Forbidden runtime dependency"):
        audit._audit_native_live_load(
            tmp_path / "sam3.bundle",
            roles,
            plan_sizes,
            probe_runner=_FakeProbeRunner(dsos, extra_mapped_dsos=(forbidden_dso,)),
        )


def test_sam3_native_live_load_rejects_unaudited_model_connect_mapping(
    tmp_path: Path,
) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    unaudited_dso = tmp_path / "libtrtmc_hidden_runtime.so"
    unaudited_dso.write_bytes(b"\x7fELFhidden")
    roles = audit._require_dso_roles(dsos)
    plan_sizes = {
        name: len(payload)
        for name, payload in _valid_section_payloads().items()
        if name in audit.SAM3_PLAN_SECTIONS
    }

    with pytest.raises(audit.Sam3RuntimeContractError, match="unaudited Model Connect DSO"):
        audit._audit_native_live_load(
            tmp_path / "sam3.bundle",
            roles,
            plan_sizes,
            probe_runner=_FakeProbeRunner(dsos, extra_mapped_dsos=(unaudited_dso,)),
        )


def test_sam3_native_live_load_allows_platform_mapping_delta(tmp_path: Path) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    platform_dso = tmp_path / "libcudnn.so.9"
    platform_dso.write_bytes(b"\x7fELFplatform")
    roles = audit._require_dso_roles(dsos)
    plan_sizes = {
        name: len(payload)
        for name, payload in _valid_section_payloads().items()
        if name in audit.SAM3_PLAN_SECTIONS
    }

    audit._audit_native_live_load(
        tmp_path / "sam3.bundle",
        roles,
        plan_sizes,
        probe_runner=_FakeProbeRunner(dsos, extra_mapped_dsos=(platform_dso,)),
    )


def test_sam3_native_live_load_surfaces_probe_process_failure(tmp_path: Path) -> None:
    dsos = _write_runtime_dsos(tmp_path)
    roles = audit._require_dso_roles(dsos)

    def failed_probe(command: Sequence[str]) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            args=list(command),
            returncode=7,
            stdout="",
            stderr="native deserialize failed",
        )

    with pytest.raises(audit.Sam3RuntimeContractError, match="native deserialize failed"):
        audit._audit_native_live_load(
            tmp_path / "sam3.bundle",
            roles,
            {name: 1 for name in audit.SAM3_PLAN_SECTIONS},
            probe_runner=failed_probe,
        )


def test_sam3_runtime_audit_cli_requires_cmake_cache() -> None:
    parser = audit._parser()

    with pytest.raises(SystemExit):
        parser.parse_args(
            [
                "--bundle",
                "sam3.bundle",
                "--dso",
                "libtrtmc_core.so",
            ]
        )
