# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "internlm"
runtime_library = "libtrtmc_model_internlm.so"
runtime_plugins = ["plugin.cpp|register_internlm_plugin"]
runtime_strategies = ["internlm_decoder_kv_cache"]
[validation_profiles]
decoder_debug = ["internlm_decoder_kv_cache"]

runtime_tests = [
  "test_internlm_chat_template|test_internlm_chat_template.cpp|trtmc_model_internlm|_|_",
]
