# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "fnet"
plugin = "fnet"
module = "plugin"
aliases = [
  "fnet",
]
prefixes = [
  "fnet",
]
