# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

foreach(_required IN ITEMS INPUT_FILE OUTPUT_FILE SYMBOL)
  if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
    message(FATAL_ERROR "embed_binary.cmake requires -D${_required}=...")
  endif()
endforeach()

if(NOT EXISTS "${INPUT_FILE}")
  message(FATAL_ERROR "Binary input does not exist: ${INPUT_FILE}")
endif()
if(NOT SYMBOL MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
  message(FATAL_ERROR "Invalid C++ binary symbol: ${SYMBOL}")
endif()

file(READ "${INPUT_FILE}" _hex HEX)
string(LENGTH "${_hex}" _hex_length)
get_filename_component(_output_directory "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_directory}")
file(WRITE "${OUTPUT_FILE}"
  "// Generated by cmake/embed_binary.cmake. Do not edit.\n"
  "#pragma once\n\n"
  "#include <cstddef>\n\n"
  "inline constexpr unsigned char ${SYMBOL}[] = {\n")

# Keep generated source lines short enough for every supported host compiler.
set(_offset 0)
while(_offset LESS _hex_length)
  math(EXPR _remaining "${_hex_length} - ${_offset}")
  if(_remaining GREATER 64)
    set(_chunk_length 64)
  else()
    set(_chunk_length ${_remaining})
  endif()
  string(SUBSTRING "${_hex}" ${_offset} ${_chunk_length} _chunk)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _chunk "${_chunk}")
  file(APPEND "${OUTPUT_FILE}" "    ${_chunk}\n")
  math(EXPR _offset "${_offset} + ${_chunk_length}")
endwhile()

# PTX consumers require a terminating NUL; it is harmless for other assets.
file(APPEND "${OUTPUT_FILE}"
  "    0x00,\n};\n"
  "inline constexpr std::size_t ${SYMBOL}Size = sizeof(${SYMBOL});\n")
