# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG MAX_JOBS=8
ENV MAX_JOBS=${MAX_JOBS}
ENV TRTMC_DEPENDENCY_IMPORTS=causal_conv1d,mamba_ssm
COPY requirements.txt /opt/trtmc-ci/nemotron_h/requirements.txt
RUN python -m pip install --disable-pip-version-check --no-cache-dir \
      --no-build-isolation --requirement /opt/trtmc-ci/nemotron_h/requirements.txt && \
    python -m pip check
