# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

id = "z_image"
aliases = [
  "z-image",
  "z_image",
  "zimage",
  "zimagepipeline",
]
prefixes = [
  "z_image",
]
diffusion_pipeline_classes = [
  "ZImagePipeline",
]
hf_allow_patterns = [
  "model_index.json",
  "scheduler/**",
  "text_encoder/**",
  "text_encoder_2/**",
  "transformer/**",
  "vae/**",
  "tokenizer/**",
  "tokenizer_2/**",
  "*/config.json",
  "*/model.safetensors",
  "*/model-*.safetensors",
  "*/model.safetensors.index.json",
  "*/diffusion_pytorch_model.safetensors",
  "*/diffusion_pytorch_model-*.safetensors",
  "*/diffusion_pytorch_model.safetensors.index.json",
  "scheduler/*",
  "tokenizer/*",
]
